import { Level } from '../types/level';

export const LEVELS_INFO: { [level: string]: Level } = {
    1: {
        maxLetters: 5,
        letters: ['E', 'S', 'P', 'O', 'R', 'T', 'E'],
        hints: [
            'É uma parte do corpo',
            'Parte de cima da casa',
            'Onde você guarda biscoitos',
            'Cor mais escura',
            'Oposto da palavra Azar',
        ],
        words: [
            { visible: false, value: 'PE' },
            { visible: false, value: 'TETO' },
            { visible: false, value: 'POTE' },
            { visible: false, value: 'PRETO' },
            { visible: false, value: 'SORTE' },
        ],
    },
    2: {
        maxLetters: 5,
        letters: ['M', 'R', 'A', 'S', 'A', 'O'],
        hints: [
            'Você precisa respirar isso',
            'Água que existe na praia',
            'Os passaros precisam disso para voar',
            'Um dos melhores sentimentos',
            '2 é o resultado da **** de 1 + 1',
        ],
        words: [
            { visible: false, value: 'AR' },
            { visible: false, value: 'MAR' },
            { visible: false, value: 'ASA' },
            { visible: false, value: 'AMOR' },
            { visible: false, value: 'SOMA' },
        ],
    },
    3: {
        maxLetters: 5,
        letters: ['E', 'S', 'R', 'A', 'E', 'I', 'T'],
        hints: [
            '*** humano',
            'Usa uma coroa',
            'Irmã da mãe de um criança, é o que dela?',
            'Aranha gosta de fazer',
            'Aquela **** aponta para longe',
            'Parece com um ser humano, mas vive no mar',
        ],
        words: [
            { visible: false, value: 'SER' },
            { visible: false, value: 'REI' },
            { visible: false, value: 'TIA' },
            { visible: false, value: 'TEIA' },
            { visible: false, value: 'SETA' },
            { visible: false, value: 'SEREIA' },
        ],
    },
    4: {
        maxLetters: 5,
        letters: ['A', 'B', 'T', 'C', 'R', 'D', 'O'],
        hints: [
            'Azul é uma ***',
            'O carro precisa disso para andar',
            'Tipo de sapato',
            'Um pequeno animal',
            'Meio de transporte do Mar',
            'Você usa para amarrar coisas',
        ],
        words: [
            { visible: false, value: 'COR' },
            { visible: false, value: 'RODA' },
            { visible: false, value: 'BOTA' },
            { visible: false, value: 'RATO' },
            { visible: false, value: 'BARCO' },
            { visible: false, value: 'CORDA' },
        ],
    },
    5: {
        maxLetters: 5,
        letters: ['L', 'T', 'A', 'A', 'C', 'O', 'S'],
        hints: [
            'Você usa para grudar coisas',
            'Esquenta o Planeta Terra',
            'Se passa no bumbum dos bebês',
            'Queria uma **** de refrigerante',
            'O urso se esconde na ****',
            'Tem no sapato para as pessoas ficarem mais altas',
            'Você pode morar nesse lugar',
            'Se usa para guardar a feira no supermercado',
        ],
        words: [
            { visible: false, value: 'COLA' },
            { visible: false, value: 'SOL' },
            { visible: false, value: 'TALCO' },
            { visible: false, value: 'LATA' },
            { visible: false, value: 'TOCA' },
            { visible: false, value: 'SALTO' },
            { visible: false, value: 'CASA' },
            { visible: false, value: 'SACOLA' },
        ],
    },
};
